### PR TITLE
Adding performance tests

### PR DESCRIPTION
**Pull request by jamesbascle**
I'd like to start working on improving performance of Matcher, Switch, and possibly the fallback case.

I've added some Matcher performance tests.  Right now the performance targets are just left blank, but are useful for reporting the number of operations that were able to be performed.  I've got some ideas on how to do so.

### CODE REVIEW

**Comment by Jagged** [comment]
The changes look good.  For things that are inferred could we please let the compiler do that so the code is clearer and less cluttered? Specifically I'm referring to adding `private` to the front of things.  Hmm, I probably should go thru things and remove `this` from most member accesses except for the ctors.

**Comment by Jagged** [comment]
Yikes, each of the performance tests takes 20secs+!  I have my system to run tests on build, so as you can imagine it's nasty!  I'm a little confused, as it appears you've set the tests to only run for 500ms each.  Do you know what's causing the long run times?

**Comment by jamesbascle** [comment]
Yeah. Basically it does a bit of setup and tear down for each iteration
that if doesn't count towarss that time. One option is to do a big loop
inside the methods, but you get less precision that way, especially with
the dynamic ones in T5 and T6.

That's why I tagged them as Unit and Performance, so that we can run them
separately.  Both the VS and R# test runners support the category
filtering/grouping I believe.

**Comment by jamesbascle** [comment]
Yeah that's why I added private, because I saw the verbosity of this
everywhere. Did you use R#? If so can u commit your settings file? If not,
just set tose members up as you prefer, and I'll set up a Resharper setting
file for it so we can more easily keep a consistent code style.

**Comment by Jagged** [comment]
No I don't use R#, I'm just using VS default settings to minimise conflicts in coding style.

**Pull request merged**
