### PR TITLE
Making performance tests run in a reasonable amount of time. Generati…

### PR DESCRIPTION
**Pull request by jamesbascle**
…ng performance tests from a T4 Template.

### CODE REVIEW

**Comment by jamesbascle** [comment]
@Jagged Give this a shot.  They're each running in ~3secs for me.  I can probably speed it up a wee bit from that as well if you'd like.

**Comment by Jagged** [comment]
Definitely a huge difference! I'm not so afraid to run the unit tests now!

**Comment by Jagged** [comment]
Could you please explain the perf tests?  Is it to test the relative performance of matching T0-T9 from the same kind of OneOf?  I see a massive drop between after "T3", and I also noticed it seems to be triggering the last match `Match(b => b.Type.ToString()` which will be quite expensive time-wise due to the ToString and effect on cache lines.

**Comment by jamesbascle** [comment]
The purpose was to trigger that behavior or a subclass that is not also in
the one of.  I hadn't really thought about that tbh - was just trying a
simple way to get a string.  Perhaps we ought, as you say, replace that
enum with some strings to make it more representative of the real perf...
Could even just make a dictionary cache I suppose, that way it's just a
hash lookup

**Comment by jamesbascle** [comment]
Oh I guess I should just make them all return a constant. No need for the
differing behavior.

**Pull request merged**
