### PR TITLE
Adding a new polymorphic test to make sure the OneOf properly binds h…

### PR DESCRIPTION
**Pull request by jamesbascle**
…ierarchies.  Simplifying type finding code in OneOfFactory by just initializing the dictionary with the types from the GenericArgsArray.

### CODE REVIEW

**Comment by Jagged** [comment]
Whoops, sorry, my commit broke your PR.  Would you mind adjusting so I can merge please?

**Comment by jamesbascle** [comment]
Sure give me a few...

**Comment by jamesbascle** [comment]
Okay I think that's done it.

**Comment by Jagged** [comment]
Thanks James.  Just as you did that I was figuring out how to correct it my end, I'm more used to SVN.

**Comment by jamesbascle** [comment]
And I Hg, but these are the times we live in :D

**Comment by Jagged** [comment]
Any progress with moving the performance tests out into something we can run a profiler against? 
ps. I'm currently getting around 12M iterations with a release build.

**Comment by jamesbascle** [comment]
Yeah. 12.3M for me. 

I'm not quite sure what you're thinkin' exactly WRT the profiler.   I just run dotTrace from R# Unit Test Session, against the tests, which is good enough for me.  What are your thoughts on the matter?

**Comment by Jagged** [comment]
I'd like to use MS's built-in profiler, but have yet to find out how to use it with unit tests.

ps Have made you a collaborator as we're both pretty much on the same page.  Hopefully it'll be a little easier for you from here for future commits.  Cheers!

**Comment by jamesbascle** [comment]
Would a separate project that is both executable and annotated with unit tests that you can unload and reload be acceptable?  I have no problem setting that up if it would work for you.

**Comment by Jagged** [comment]
In a nutshell that sounds awesome, that way the perf tests become opt-in and also can be profiled.

**Comment by jamesbascle** [comment]
Hey sorry i've gone radio silent. lots of stuff on my plate atm. hoping to
get to this in next week or so.

**Comment by Jagged** [comment]
That's fine James, who knew there would be life outside this?!

**Pull request merged**
